# Random Matrices in NumPy

---

## 1. Theory of Distribution Types

### Uniform Continuous Distribution `[0, 1)`
* **The Math**: Every real number within the half-open interval `[0, 1)` has a completely equal probability density. It follows the probability density function (PDF):
  $$f(x) = \begin{cases} 1 & \text{for } 0 \le x < 1 \\ 0 & \text{otherwise} \end{cases}$$
* **Matrix Properties**: As the dimensions approach infinity, the expected average value of all elements in the matrix converges precisely to `0.5`, and the variance converges to `1/12 ≈ 0.0833`.

### Standard Normal (Gaussian) Distribution
* **The Math**: Elements are sampled from a continuous bell curve symmetric around zero. It follows the PDF:
  $$f(x) = \frac{1}{\sqrt{2\pi}} e^{-\frac{x^2}{2}}$$
* **Matrix Properties**: The expected mean of the matrix elements is `0`, and the variance is `1`. In Random Matrix Theory, a square matrix filled with these independent and identically distributed (i.i.d.) normal variables forms the foundational building block for complex statistical physics frameworks, such as the Ginibre Ensemble.

### Discrete Uniform Distribution
* **The Math**: Elements are sampled from a finite set of integers where each integer has a probability of exactly `1 / (high - low)`. 
* **Matrix Properties**: This constructs discrete random networks, digital state matrices, or combinatorial systems.

---

## 2. Matrix Addition & The Broadcasting Theory

When performing element-wise addition ($A + B$), linear algebra strictly dictates that both matrices must share identical dimensions. NumPy bypasses this via **Broadcasting Theory**, which establishes strict logical rules for element alignment without copying data in memory.

### The Core Rules of Broadcasting
1. **Dimension Alignment**: NumPy compares the shapes of both matrices element-by-element, moving **backwards** from the trailing (rightmost) dimensions.
2. **Compatibility Test**: Two dimensions are compatible only if:
   * They are exactly equal in size, OR
   * One of the dimensions is exactly `1`.
3. **Virtual Expansion**: If a dimension is exactly `1`, that dimension is logically stretched or replicated to match the larger dimension of the other matrix.

### Concrete Broadcasting Example
- `A.shape = (3, 3)`, `B.shape = (1, 3)`
- Compare trailing dimensions: `3` (from A) and `3` (from B) → compatible (equal).
- Next: `3` (from A) and `1` (from B) → compatible because one is `1`.  
- Result: `B` is virtually stretched to `(3, 3)` and added element‑wise to `A`.

---

## 3. Matrix Multiplication Topology

The algebraic operation $A \times B$ represents a geometric linear transformation, not an element-by-element operation.

### The Inner Dimension Constraint
Multiplication is only mathematically defined when the inner dimensions match: $(m \times n) \times (n \times p) = (m \times p)$.
* **The "n" dimension**: Represents the shared vector space.
* **The Dot Product Engine**: The value at coordinate $(i, j)$ in the resulting matrix is calculated by taking the dot product of the $i$-th row of Matrix A and the $j$-th column of Matrix B:
  $$C_{i,j} = \sum_{k=1}^{n} A_{i,k} B_{k,j}$$

---

## 4. Transposition Theory

The transpose operation ($A^T$) represents a fundamental spatial reflection across the main diagonal of a matrix.

### Coordinate Mapping
* **Geometric Inversion**: Every element at coordinate $(i, j)$ is mapped directly to coordinate $(j, i)$.
* **Dimension Swap**: An $m \times n$ matrix is transformed into an $n \times m$ matrix.
* **Mathematical Properties**: 
  - Transposition distributes across addition: $(A + B)^T = A^T + B^T$
  - It reverses the order of multiplication: $(AB)^T = B^T A^T$
  - **Involution**: $(A^T)^T = A$

---

## 5. Special Note for Day 2 – Linear Algebra Operations

Operations like **determinant**, **inverse**, and **eigenvalues** are defined only for **square matrices** ($n \times n$). When we use `np.linalg.det`, `np.linalg.inv`, or `np.linalg.eig`, the input must be square; otherwise NumPy raises a `LinAlgError`.



In [1]:
import numpy as np 

"""
1. Continuous Uniform Distribution [0.0, 1.0):
    Generates floating-point numbers where every value in the interval has an equal probability.
    output range : [0.0,1.0)

"""
#Initialize the gernartor
rng=np.random.default_rng()

#creating a uniform 3x3 matrix
uniform_matrix=rng.random(size=(3,3))
print("Using continous Uniform Distribution : ","\n",uniform_matrix)


"""
2. Standard Normal (Gaussian) Distribution:
    Generates floating-point numbers following a bell curve centered at a mean of 0 with a standard deviation (variance) of 1.
    output range : (-∞,+∞)
"""

normal_matrix=rng.standard_normal(size=(3,3))
print("Using Gaussian Distribution : ","\n",normal_matrix)


"""
3. Discrete Uniform Integers:
    Generates random whole numbers within a specific range. The low limit is inclusive, while the high limit is exclusive.
    output range : [low,high)

""" 

integer_matrix=rng.integers(low=2,high=99,size=(3,3))
print("Using Discrete Uniform Integers : ","\n",integer_matrix)



Using continous Uniform Distribution :  
 [[0.45901097 0.79664011 0.60109687]
 [0.21896609 0.56980611 0.3670729 ]
 [0.10078662 0.30146333 0.29725287]]
Using Gaussian Distribution :  
 [[ 0.529176   -1.22255898 -0.28920273]
 [-0.2676057  -0.55040489  0.22753396]
 [ 0.51418191  0.37225346  1.83313188]]
Using Discrete Uniform Integers :  
 [[15 79 77]
 [61 56 30]
 [20 46 29]]


# Truly Random ?
Computers can't generate truly random numbers.
They use mathematical algorithms to create "pseudo-random" sequences

To lock randomness in genrated matrix use **seed** for exact reproducibility.

## Reproducibility using Seeds
By setting a seed value, it  force the generator engine to start at the exact same point in its mathematical sequence every time.

#### Why Use a Seed?

* **Debugging:** When code crashes on a specific random matrix, a seed allows to regenerate that exact same matrix to find the bug.
* **Scientific Benchmarking:** When comparing two different algorithms, it must be test on the exact same data to ensure a fair comparison.

In [3]:
#Genrating two same random Matrices

#Initialize the generator with an explicit seed integer
rng1=np.random.default_rng(seed=55)
matrix_A = rng1.standard_normal(size=(3,2))

#Initializing the second genrator with exact same seed 
rng2=np.random.default_rng(seed=55)
matrix_B = rng2.standard_normal(size=(3,2))

if np.array_equal(matrix_A,matrix_B):
    print("Genrated Matrices are equal :")
    print("Matrix A : ","\n",matrix_A,"\n","Matrix B : ","\n",matrix_B)
else:
    print("Genrated Matrices are NOT equal")    

Genrated Matrices are equal :
Matrix A :  
 [[ 0.84226132 -2.97611117]
 [-0.30502388  1.44988792]
 [-1.24396147  0.0532106 ]] 
 Matrix B :  
 [[ 0.84226132 -2.97611117]
 [-0.30502388  1.44988792]
 [-1.24396147  0.0532106 ]]


# Complex-Valued Random Matrices

Used mostly in  engineering and physics, matrices often require complex numbers containing both a real part ($a$) and an imaginary part ($bi$, where $i = \sqrt{-1}$).


#### How to Construct a Complex Random Matrix

NumPy does not have a single direct function for complex numbers. Instead, we can generate the real matrix and the imaginary matrix independently, then mathematically combine them.



In [4]:
rng = np.random.default_rng(seed=56)

#Shape configuration
rows,cols=3,3

#Real component 
real_part=rng.standard_normal((rows,cols))

#imaginary component
imag_part=rng.standard_normal((rows,cols))

#Combining real and imaginary parts
complex_matrix = real_part + 1j * imag_part

print("Randomly genrated complex Matrix :","\n",complex_matrix)


"""
In phyical systems, Matrices must often be Hermitian(equal to their own conjugate transpose i.e  H = H† )

To obtain Hermitian matrix (H) :

        H= ( A+A† )/2
        
    Note: 1. Divion by 2 does not affect the symmetry at all, it only affects the scale of number i.e. preserving the real part only in digonal
            elements of H. 
            
          2. The diagonal elements of Hermetian Matrix is always real.         
"""

Hermetian_matrix=(complex_matrix + complex_matrix.conj().T)/2
print("Hermetian Matrix : ","\n",Hermetian_matrix)


Randomly genrated complex Matrix : 
 [[-0.84994072+0.12535155j  0.32194085+0.54422123j  1.78904286-0.67382748j]
 [ 0.8793392 +0.01964472j  0.37159282-1.05808512j  1.48769378-1.34806622j]
 [ 0.72866553+1.21982602j  2.08124873-2.40019087j -1.33726808-1.55657975j]]
Hermetian Matrix :  
 [[-0.84994072+0.j          0.60064002+0.26228825j  1.25885419-0.94682675j]
 [ 0.60064002-0.26228825j  0.37159282+0.j          1.78447126+0.52606232j]
 [ 1.25885419+0.94682675j  1.78447126-0.52606232j -1.33726808+0.j        ]]


In [ ]:
import numpy as np 
rng= np.random.default_rng()#add sedd="integer"  in required fixed matrix

def genrate_matrix(rows,cols):
    
    if rows!=cols:
        raise ValueError("Expected: Square matrix!")
    
    matrix_m=rng.standard_normal(size=(rows,cols))

    #making symmetric matrix
    A=(matrix_m + matrix_m.T)/2
    #determinant of A
    det_A=np.linalg.det(A)
    
    return A,det_A

def eigen_val_vec(A):
    
    eigvals,eigvecs = np.linalg.eig(A)
    
    for i in range(len(eigvals)):
        print ("Eigen value :",eigvals[i]," --> ","Eigen Vector :",eigvecs[:,i])
    
    #verification for first eigen pair
    lamb_0=eigvals[0]
    v0=eigvecs[:,0]
    
    left = A@v0
    right = lamb_0 * v0 
    
    return np.allclose(left,right)

def get_inverse(A):
    
    invA=np.linalg.inv(A)
    print("Inverse of Matrix A : ","\n",invA)
    
    #Verification A * inv(A) should be identity
    
    ident_check = A @ invA
    
    return np.allclose(ident_check,np.eye(A.shape[0]))
        
    
    
try:
    rows,cols=6,6
    A,det_A = genrate_matrix(rows,cols)
    print("Genrated Matrix :","\n",A,"\n","determinant : ",det_A,"\n")
        
        
    if np.abs(det_A)>1e-10:
        print("Matrix is non-singular and invertible :")
        
        #Inverse of A and verification
        print("Is close to identity? : ",get_inverse(A))
        
        #Eigen value and vector and verification of eigenvalue equation
        print("Eigenvalue equation holds? : ",eigen_val_vec(A))
            
    else:
        print("Matrix is singular, can't invert!")
        
except ValueError as e:
    # This catches  intended exception so the script finishes cleanly
    print(f"Caught expected error: {e}")            
        




Caught expected error: Expected: Square matrix!


In [11]:
#checking the singularity of matrix by determinant
rng=np.random.default_rng(seed=42)

def is_singular(A, tol=1e-10):
    
    if A.shape[0] != A.shape[1]:
        raise ValueError("Expected: Square matrix!")
    
    #determinant of A
    det_A = np.linalg.det(A)
    
    #A matrix is considered singular if its determinant is close to zero (within a specified tolerance).
    return np.abs(det_A) < tol


#genrating a random 3x3 matrix and checking its singularity
rows,cols=3,3

A=rng.standard_normal((rows,cols))
det_A=np.linalg.det(A)

print("Genrated Matrix :","\n",A,"\n","determinant : ",det_A)
print("Is singular? : ",is_singular(A))





Genrated Matrix : 
 [[ 0.30471708 -1.03998411  0.7504512 ]
 [ 0.94056472 -1.95103519 -1.30217951]
 [ 0.1278404  -0.31624259 -0.01680116]] 
 determinant :  0.005156749341926485
Is singular? :  False
