

## Problem Statement

The objective is to solve a system of linear equations represented by $Ax = b$, where $A$ is an $n \times n$ square matrix, $x$ is the vector of unknown variables, and $b$ is the constant vector. We achieve this by factoring the matrix $A$ into the product of a lower triangular matrix $L$ and an upper triangular matrix $U$.

Once decomposed, the original system $LUx = b$ can be solved in two computationally efficient steps:
1.  Solve $Ly = b$ for $y$ using forward substitution.
2.  Solve $Ux = y$ for $x$ using backward substitution.

---

## Mathematical Theory

**LU Decomposition (Doolittle Algorithm)** assumes that the diagonal elements of the lower triangular matrix $L$ are all $1$. 

Given $A = LU$:
$$A = \begin{bmatrix} 1 & 0 & 0 \\ l_{21} & 1 & 0 \\ l_{31} & l_{32} & 1 \end{bmatrix} \begin{bmatrix} u_{11} & u_{12} & u_{13} \\ 0 & u_{22} & u_{23} \\ 0 & 0 & u_{33} \end{bmatrix}$$

By performing matrix multiplication and equating the elements to matrix $A$, we can systematically solve for the unknown elements of $U$ (row by row) and $L$ (column by column).

---

## Formulas for Decomposition

To compute the elements of the **Upper Triangular Matrix $U$** (for $j \geq i$):
$$u_{ij} = a_{ij} - \sum_{k=0}^{i-1} l_{ik}u_{kj}$$

To compute the elements of the **Lower Triangular Matrix $L$** (for $j > i$):
$$l_{ji} = \frac{1}{u_{ii}} \left( a_{ji} - \sum_{k=0}^{i-1} l_{jk}u_{ki} \right)$$

---

## Formulas for Substitution

**Forward Substitution** ($Ly = b$):
$$y_i = b_i - \sum_{k=0}^{i-1} l_{ik}y_k \quad \text{for } i = 0, 1, \dots, n-1$$

**Backward Substitution** ($Ux = y$):
$$x_i = \frac{1}{u_{ii}} \left( y_i - \sum_{k=i+1}^{n-1} u_{ik}x_k \right) \quad \text{for } i = n-1, n-2, \dots, 0$$

---

## Algorithm Steps

1.  **Validation:** Ensure matrix $A$ is an $n \times n$ square matrix.
2.  **Initialization:**
    * Create an $n \times n$ identity matrix for $L$.
    * Create an $n \times n$ zero matrix for $U$.
3.  **Decomposition Loop:** For each step $i$ from $0$ to $n-1$:
    * **Compute Row $i$ of $U$:** Iterate $j$ from $i$ to $n-1$. Calculate $u_{ij}$ using the dot product of the previously computed elements of $L$'s $i$-th row and $U$'s $j$-th column.
    * **Compute Column $i$ of $L$:** Iterate $j$ from $i+1$ to $n-1$. Calculate $l_{ji}$ using the dot product of the previously computed elements of $L$'s $j$-th row and $U$'s $i$-th column, divided by the pivot $u_{ii}$. (Raise an error if the pivot is zero).
4.  **Forward Substitution:** Iterate $i$ from $0$ to $n-1$ to solve for the intermediate vector $y$.
5.  **Backward Substitution:** Iterate $i$ backwards from $n-1$ to $0$ to solve for the final solution vector $x$.

In [2]:
import numpy as np

def lu_decompotion_Mformula(A):
    
    if A.shape[0]!=A.shape[1]:
        raise ValueError ("Matrix Must be square.")
    
    n=len(A)
    l=np.identity(n)
    u=np.zeros((n,n))

    for i in range(n):
    
        #computing row i of matrix u
        for j in range(i,n):
            # l[i, :i] gets row elements up to column i
            # u[:i, j] gets column elements up to row i
            u[i,j]=A[i,j]- np.dot(l[i, :i], u[:i, j])
    
        #computing the ith coloumn of matrix l    
        for j in range(i+1,n):
            # l[j, :i] gets row elements up to column i
            # u[:i, i] gets column elements up to row i
            pivate=u[i,i]
            if pivate==0:
                raise ValueError ("Can't divide by zero")
            
            l[j,i]=(A[j,i]-np.dot(l[j, :i], u[:i, i]))/pivate
            
    return l,u

def find_unknown(l,u,b):
    n=len(b)
    
    y=np.zeros(n)
    x=np.zeros(n)
    
    #forward substituion
    for i in range(n):
        y[i]=b[i]-np.dot(l[i,:i],y[:i]) 
    
    #backword substituion
    for i in range(n-1,-1,-1):
        pivate=u[i,i]
        if pivate==0:
            raise ValueError ("Can't divide by zero")
        x[i]=(y[i]-np.dot(u[i,i+1:],x[i+1:]) )/pivate
          
    return y,x
   
   
try:    

    #-----------------------------------------                 
    #              Test case 1
    #-----------------------------------------
    A=np.array([[2,-1,-2],
                [-4,6,3],
                [-4,-2,8]])

    b=np.array([-1,13,-6])

    l,u=lu_decompotion_Mformula(A) 
    y,x=find_unknown(l,u,b) 

    print("Test case :-1")
    print("Matrix L :","\n",l)
    print("Matrix U :","\n",u)           
    print("Forward Substitution Vector y:\n", y)
    print("\nBackward Substitution Solution Vector x:\n", x)


    #-----------------------------------------                 
    #              Test case 2
    #-----------------------------------------


    A = np.array([
        [ 2,  1, -1,  0,  3],
        [ 4,  5,  0,  2,  7],
        [-2,  5,  8,  1,  0],
        [ 6,  9,  4,  6, 17],
        [ 0,  6, 10, -7,  1]
    ])

    b = np.array([13, 46, 34, 116, 32])


    l, u = lu_decompotion_Mformula(A)
    y, x = find_unknown(l, u, b)
    print("Test case :-2")
    print("Matrix L :","\n",l)
    print("Matrix U :","\n",u)   
    print("Forward Substitution Vector y:\n", y)
    print("\nBackward Substitution Vector x:\n", x)
    
except ValueError as e:
    print(f"Error : {e}")
    

              

Test case :-1
Matrix L : 
 [[ 1.  0.  0.]
 [-2.  1.  0.]
 [-2. -1.  1.]]
Matrix U : 
 [[ 2. -1. -2.]
 [ 0.  4. -1.]
 [ 0.  0.  3.]]
Forward Substitution Vector y:
 [-1. 11.  3.]

Backward Substitution Solution Vector x:
 [2. 3. 1.]
Test case :-2
Matrix L : 
 [[ 1.  0.  0.  0.  0.]
 [ 2.  1.  0.  0.  0.]
 [-1.  2.  1.  0.  0.]
 [ 3.  2.  1.  1.  0.]
 [ 0.  2.  2. -1.  1.]]
Matrix U : 
 [[ 2.  1. -1.  0.  3.]
 [ 0.  3.  2.  2.  1.]
 [ 0.  0.  3. -3.  1.]
 [ 0.  0.  0.  5.  5.]
 [ 0.  0.  0.  0.  2.]]
Forward Substitution Vector y:
 [13. 20.  7. 30.  8.]

Backward Substitution Vector x:
 [1. 2. 3. 2. 4.]


## Verification: Matrix Reconstruction ($L \times U = A$)

To confirm the decomposition is mathematically correct, we multiply the calculated matrices $L$ and $U$. We then use `np.allclose()` to verify if the product $LU$ matches the original coefficient matrix $A$ within numerical precision.


In [8]:
def verify_lu(l,u,A):
    #verify L@U=A
    
    left=l@u
    print("Lower Triangular Matrix (L) :","\n",l,"\n")
    print("Upper Triangular Matrix (U) :","\n",u,"\n")
    print("L @ U : ","\n",left)
    print("coefficent Matrix (A) = ","\n",A,)
    
    return np.allclose(left,A)


A=np.array([[2,-1,-2],
            [-4,6,3],
            [-4,-2,8]])

b=np.array([-1,13,-6])

l,u=lu_decompotion_Mformula(A) 


print("\n","Is close ? : ",verify_lu(l,u,A))    
    

Lower Triangular Matrix (L) : 
 [[ 1.  0.  0.]
 [-2.  1.  0.]
 [-2. -1.  1.]] 

Upper Triangular Matrix (U) : 
 [[ 2. -1. -2.]
 [ 0.  4. -1.]
 [ 0.  0.  3.]] 

L @ U :  
 [[ 2. -1. -2.]
 [-4.  6.  3.]
 [-4. -2.  8.]]
coefficent Matrix (A) =  
 [[ 2 -1 -2]
 [-4  6  3]
 [-4 -2  8]]

 Is close ? :  True


## Verification using SciPy (`scipy.linalg.lu`)
 
 validating  manual implementation against SciPy's built-in LU decomposition tool. Because SciPy utilizes **partial pivoting** for numerical stability, it outputs a permutation matrix $P$ alongside $L$ and $U$, satisfying the equation $P L U = A$.


In [16]:
from scipy.linalg import lu

# SciPy's LU with partial pivoting
# P is permutation matrix
P, L, U = lu(A)
print(" P@L@U : ","\n",P @ L @ U,"\n")
\
print("coefficent Matrix (A) = ","\n",A,)
  
print("Is close to A?", np.allclose(P @ L @ U, A))

 P@L@U :  
 [[ 2. -1. -2.]
 [-4.  6.  3.]
 [-4. -2.  8.]] 

coefficent Matrix (A) =  
 [[ 2 -1 -2]
 [-4  6  3]
 [-4 -2  8]]
Is close to A? True


## Limitations & Edge Cases

### 1. Division by Zero (Zero Pivot)
* **The Problem:** The algorithm divides directly by the diagonal pivot element $u_{ii}$.
* **The Result:** If any pivot becomes exactly $0$ during calculation, the code crashes instantly.
* **Example:** For the matrix $A = \begin{bmatrix} 0 & 1 \\ 1 & 1 \end{bmatrix}$, the first pivot $u_{00}$ is $0$, making the calculation of $l_{10}$ impossible despite a valid unique solution existing.

### 2. Numerical Instability (Near-Zero Pivot)
* **The Problem:** Computers use finite floating-point precision to store numbers.
* **The Result:** If a pivot $u_{ii}$ is extremely small (e.g., $10^{-16}$), dividing by it explodes the remaining values and triggers massive round-off errors.
* **Example:** For the matrix $A = \begin{bmatrix} 10^{-16} & 1 \\ 1 & 1 \end{bmatrix}$, the small pivot blows up numbers, drops trailing digits, and completely corrupts the final output vector.

### 3. Strictly Square Matrices Only
* **The Problem:** The core loop structures and index bounds explicitly assume a size of $n \times n$.
* **The Result:** Passing a rectangular matrix ($m \times n$) causes the code to throw an `IndexError` or compute incorrect dimensions.


## Next Update: LU Decomposition via Gaussian Elimination with Partial Pivoting

### 🚀 Upcoming Feature
We will implement an advanced LU Decomposition method utilizing **Gaussian Elimination with Partial Pivoting (PA = LU)**. 

### 💡 Why This Matters
* **Fixes Zero Pivots:** Row swapping prevents division-by-zero crashes when zeros appear on the diagonal.
* **Maximizes Numerical Stability:** Selecting the largest available absolute value as the pivot minimizes floating-point round-off errors.
* **Handles Complex Systems:** This robust approach allows the algorithm to safely process a much wider variety of matrices without failing.
